project:
  type: website
  output-dir: docs

website:
  title: "Siri Sagedahl"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - sidebar:maps
      
  sidebar: 
  - id: Maps
      
page-footer:
    left: |
      &copy; Siri Sagedahl, 2024<br>
      All content licensed under <i class='bi-badge-cc'></i>
      [(CC BY-NC-SA 4.0)](http://creativecommons.org/licenses/by-nc-sa/4.0/)
    right: |
      Site built with <a href='https://quarto.org/'>Quarto</a>

format:
  html:
    theme: quartz
    css: styles.css
    toc: true

editor: visual

