project:
  type: website
  output-dir: docs

website:
  title: "Siri Sagedahl"
  navbar:
    background: primary
    search: true
    left:
      - href: index.qmd
        text: Home
      - sidebar:projects
      
  sidebar: 
  - id: maps
    title: "Projects"
    contents:
    - mini_project_1.qmd
    - state_dat_choropleth.qmd
    - mini_project2.qmd
    
page-footer:
    left: |
      &copy; Siri Sagedahl, 2024<br>
      All content licensed under <i class='bi-badge-cc'></i>
      [(CC BY-NC-SA 4.0)](http://creativecommons.org/licenses/by-nc-sa/4.0/)
    right: |
      Site built with <a href='https://quarto.org/'>Quarto</a>

format:
  html:
    theme: lux
    css: styles.css
    toc: true

editor: visual

