---
title: "Project 1: Maps"
author: "Siri Sagedahl"
format: html
editor: visual
---

```{r}
#| message: false
#| warning: false

library(tidyverse)
library(mdsr)
library(viridis)
```

```{r}
#| message: false
#| warning: false

library(poliscidata)
library(maps)

us_states <- map_data("state")
state_data <- as_tibble(poliscidata::states) |>
  mutate(state_name = str_squish(str_to_lower(as.character(state))))

us_states |>
  mutate(region = str_replace(region, " ", "")) |>
  full_join(state_data, join_by("region" == "state_name")) |>
  ggplot(mapping = aes(x = long, y = lat,
                          group = group)) + 
  geom_polygon(aes(fill = uninsured_pct), color = "black") + 
  labs(fill = "Percentage Without Health Insurance",
       title = "Percentage of Population Without Health Insurance") +
  coord_map() + 
  theme_bw() +  
  scale_fill_gradient2() 
```
From this chloropleth map displaying the percentage of states' population without health insurance, we can observe that there is a general pattern of the southern United States having a greater percentage uninsured. The lowest percentage of uninsured population is Massachusetts while the greatest percentage of unisured population is Texas.

```{r}
#| message: false
#| warning: false

library(fec16)

results_house |>
  group_by(state, district_id) |>
  summarize(N = n())
```

```{r}
#| message: false
#| warning: false
district_elections <- results_house |>
  mutate(district = parse_number(district_id)) |>
  group_by(state, district) |>
  summarize(
    #N = n(), 
    total_votes = sum(general_votes, na.rm = TRUE),
    d_votes = sum(ifelse(party == "DEM", general_votes, 0), na.rm = TRUE),
    r_votes = sum(ifelse(party == "REP", general_votes, 0), na.rm = TRUE),
    .groups = "drop"
  ) |>
  mutate(
    other_votes = total_votes - d_votes - r_votes,
    r_prop = r_votes / total_votes,
    d_prop = d_votes / total_votes,
    other_prop = other_votes / total_votes,
    winner = ifelse(r_votes > d_votes, "Republican", "Democrat")
  )
wi_results <- district_elections |>
  filter(state == "WI")
wi_results |>                  
  select(-state)
```

```{r}
#| message: false
#| warning: false
wi_results |>
  skim(total_votes) |>
  select(-na)
```
```{r}
#| message: false
#| warning: false
wi_results |>
  summarize(
    N = n(), 
    state_votes = sum(total_votes), 
    state_d = sum(d_votes), 
    state_r = sum(r_votes)
  ) |>
  mutate(
    d_prop = state_d / state_votes, 
    r_prop = state_r / state_votes
  )
```

```{r}
#| message: false
#| warning: false
wi_results |>
  select(district, r_prop, d_prop, other_prop, winner) |>
  arrange(desc(r_prop))
```

```{r}
#| message: false
#| warning: false
library(sf)
src <- "http://cdmaps.polisci.ucla.edu/shp/districts113.zip"
lcl_zip <- fs::path(tempdir(), "districts113.zip")
download.file(src, destfile = lcl_zip)
lcl_districts <- fs::path(tempdir(), "districts113")
unzip(lcl_zip, exdir = lcl_districts)
dsn_districts <- fs::path(lcl_districts, "districtShapes")
st_layers(dsn_districts)
```

```{r}
#| message: false
#| warning: false
districts <- st_read(dsn_districts, layer = "districts113") |>
  mutate(DISTRICT = parse_number(as.character(DISTRICT)))
```
```{r}
#| message: false
#| warning: false
head(districts, width = Inf)
```

```{r}
#| message: false
#| warning: false
class(districts)
```
```{r}
#| message: false
#| warning: false
wi_shp <- districts |>
  filter(STATENAME == "Wisconsin")
wi_shp |>
  st_geometry() |>
  plot(col = gray.colors(nrow(wi_shp)))
```

```{r}
#| message: false
#| warning: false
wi_merged <- wi_shp |>
  st_transform(4326) |>
  inner_join(wi_results, by = c("DISTRICT" = "district"))
head(wi_merged, width = Inf)
```

```{r}
#| warning: false
library(ggspatial)
wi <- ggplot(data = wi_merged, aes(fill = winner)) +
  annotation_map_tile(zoom = 6, type = "osm", progress = "none") + 
  geom_sf(alpha = 0.5) +
  scale_fill_manual("Winner", values = c("blue", "red")) + 
  geom_sf_label(aes(label = DISTRICT), fill = "white") + 
  theme_void()
wi
```

```{r}
#| warning: false
wi +
  aes(fill = r_prop) + 
  scale_fill_distiller(
    "Proportion\nRepublican", 
    palette = "RdBu", 
    limits = c(0.2, 0.8)
  )
```

```{r}
#| warning: false
# A leaflet map can allow us to zoom in and see where major cities fit, etc.
library(leaflet)
pal <- colorNumeric(palette = "RdBu", domain = c(0, 1))

leaflet_wi <- leaflet(wi_merged) |>
  addTiles() |>
  addPolygons(
    weight = 1, fillOpacity = 0.7, 
    color = ~pal(1 - r_prop),   # so red association with Reps
    popup = ~paste("District", DISTRICT, "</br>", round(r_prop, 4))
  ) |>                          # popups show prop Republican
  setView(lng = -80, lat = 35, zoom = 7)
leaflet_wi

```

