---
title: "R Tip of the Day"
author: "Siri Sagedahl"
date: "2024-03-04"
output: html_document
---
```{r, message=FALSE}
library(tidyverse)
```


```{r}
ggplot(faithful, aes(x = eruptions, y = waiting)) +
 geom_point() +
  labs(x = "Duration of Eruption (Min.)", y = "Waiting Time to Next Eruption (Min.)", title = "Scatterplot of Old Faithful Eruption Data") +
 xlim(0.5, 6) +
 ylim(40, 110)
```

```{r}
ggplot(faithful, aes(x = eruptions, y = waiting)) +
 geom_point() +
  labs(x = "Duration of Eruption (Min.)", y = "Waiting Time to Next Eruption (Min.)", title = "Scatterplot with Contours of Old Faithful Eruption Data") +
 xlim(0.5, 6) +
 ylim(40, 110) +
  geom_density_2d()
```

```{r}
ggplot(faithful, aes(x = eruptions, y = waiting)) +
 geom_point() +
  labs(x = "Duration of Eruption (Min.)", y = "Waiting Time to Next Eruption (Min.)", title = "Filled Contour Map of Old Faithful Eruption Data") +
 xlim(0.5, 6) +
 ylim(40, 110) +
  geom_density_2d_filled(alpha = 0.5)
```

```{r}
ggplot(faithful, aes(x = eruptions, y = waiting)) +
 geom_point() +
  labs(x = "Duration of Eruption (Min.)", y = "Waiting Time to Next Eruption (Min.)", title = "Filled Contour Map of Old Faithful Eruption Data w/ Lines") +
 xlim(0.5, 6) +
 ylim(40, 110) +
  geom_density_2d_filled(alpha = 0.5) +
  geom_density_2d(linewidth = 0.25, color = "black")
```

```{r}
set.seed(4393)
dsmall <- diamonds[sample(nrow(diamonds), 1000), ]
dsmall |>
  ggplot(aes(x, y)) +
  geom_density_2d(aes(colour = cut)) +
  labs(x = "Length (mm)", y = "Width (mm)", title = "Size of Diamond by Cut")
```

```{r}
dsmall |>
  ggplot(aes(x, y)) +
  geom_density_2d_filled() +
  facet_wrap(vars(cut)) +
  labs(x = "Length (mm)", y = "Width (mm)", title = "Size of Diamond by Cut")
```

```{r}
dsmall |>
  ggplot(aes(x, y)) +
  geom_density_2d_filled(contour_var = "ndensity") + facet_wrap(vars(cut)) +
  labs(x = "Length (mm)", y = "Width (mm)", title = "Size of Diamond by Cut (intensity standardized)")
```

```{r}
dsmall |>
  ggplot(aes(x, y)) +
  stat_density_2d(geom = "raster",
                  aes(fill = after_stat(density)),
                  contour = FALSE) +
  scale_fill_viridis_c() +
  labs(x = "Length (mm)", y = "Width (mm)", title = "Size of Diamond by Cut")
```

```{r}
dsmall |>
  ggplot(aes(x, y)) +
  stat_density_2d(geom = "point", 
                  aes(size = after_stat(density)),
                  n = 20,
                  contour = FALSE) +
  labs(x = "Length (mm)", y = "Width (mm)", title = "Size of Diamond by Cut")
```

